### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by Nopzen**
_Work in progress. We're still working on some features to add_

# Todo
 - [x] Merge axios
 - [x] Make release notes in this PR
 - [x] Fix failing tests from `master`
 - [x] Test run in application

# Redux JSON API v2.0 Relase notes

### Changelog v1.x - v2.
- Response object no longer just sends the data, but sends a object containing data + handlers for prev and next pagination. #21
- Authentication header with "Bearer" is now configurable, as not all users want this setup. #41
- The backbone of the library have been moved from `fetch` to `axios`, this will require changes to the clients configuration #41
- Callbacks `onError` and `onSuccess` have been changed to use `then()` and `catch()`. All CRUD API's now return a promise that can be handle by the clients. #48
- Taxonomy for API's to follow the JSON API spec.
  - `createEntity` -> `createResource`
  - `updateEntity` -> `updateResource`
  - `deleteEntity` -> `deleteResource`
_Note that `readEndpoint` remains **unchanged**_. #83
- Added Store hydrator, ability to hydrate store with a initial payload https://github.com/dixieio/redux-json-api/pull/129

### Removed
- Removed deprecation warning telling that `onError` and `onSuccess` have been removed. (See changed). #48
- Upload File API
The upload file api have been remove due to its non-json api specific relation, and shoul be handle with users own implementation going forward. #26

### CODE REVIEW

**Comment by Nopzen** [comment]
Im abit late to the party, but `v2.0.0` is in beta, this PR is solely for keeping track before the v2 is ready and battle tested.

Should the urge rise to fix some bug, please branch of `2.0` and then follow the regular drill :)

**Comment by Nopzen** [comment]
Added #129 - To Release notes.

**Comment by Nopzen** [comment]
@tomharvey as you where discussing in #156, we should maybe add a todo note here that we should update the Readme with a link to your demo setup, so users could easily try this tool out. 

Now I've been a way from some time from this repo, but i read through your demo setup and it seemed pretty acurate, are there anything you know personally that is missing?

@egeriis should i update the Read me with a link to the repo mentioned above?

**Comment by egeriis** [comment]
@Nopzen Should already be in v2.0 branch?

**Pull request merged**
